### ISSUE TITLE
Comod in Deep Dark dimension

### ISSUE THREAD

**Issue by purpleposeidon** [gegy1000/PracticalSpaceFireworks#4]
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at net.minecraft.world.World.func_175644_a(World.java:3032)
	at net.gegy1000.psf.server.modules.ModuleEntityDetector.onSatelliteTick(ModuleEntityDetector.java:64)
	at net.gegy1000.psf.api.ISatellite.tickSatellite(ISatellite.java:87)
	at net.gegy1000.psf.server.ServerEventHandler.lambda$onWorldUpdate$0(ServerEventHandler.java:33)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at net.gegy1000.psf.server.ServerEventHandler.onWorldUpdate(ServerEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_113_ServerEventHandler_onWorldUpdate_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Gegy** [comment]
This seems like an issue with some other mod modifying the entity list on another thread. Hard to know what mod is doing it, though.
