### ISSUE TITLE
Crash when using orbital laser on SteamAgeRevolution.

### ISSUE THREAD

**Issue by purpleposeidon** [gegy1000/PracticalSpaceFireworks#5]
I think this happens when it hits one of their ores. Maybe it's the other guy's fault?

```
java.lang.NullPointerException: null
	at com.teamacronymcoders.base.util.ItemStackUtils.isValid(ItemStackUtils.java:29) ~[ItemStackUtils.class:?]
	at com.teamacronymcoders.base.materialsystem.blocks.SubBlockOrePart.getDrops(SubBlockOrePart.java:70) ~[SubBlockOrePart.class:?]
	at com.teamacronymcoders.base.subblocksystem.blocks.BlockSubBlockHolder.getDrops(BlockSubBlockHolder.java:96) ~[BlockSubBlockHolder.class:?]
	at net.minecraft.block.Block.getDrops(Block.java:1300) ~[aow.class:?]
	at net.minecraft.block.Block.func_180653_a(Block.java:571) ~[aow.class:?]
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:231) ~[amp.class:?]
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1169) ~[oo.class:?]
	at net.minecraft.world.World.func_72876_a(World.java:2297) ~[amu.class:?]
	at net.gegy1000.psf.server.modules.ModuleSpaceLaser.onSatelliteTick(ModuleSpaceLaser.java:74) ~[ModuleSpaceLaser.class:?]
	at net.gegy1000.psf.api.ISatellite.tickSatellite(ISatellite.java:87) ~[ISatellite.class:?]
	at net.gegy1000.psf.server.ServerEventHandler.lambda$onWorldUpdate$0(ServerEventHandler.java:33) ~[ServerEventHandler.class:?]
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0_162]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080) ~[?:1.8.0_162]
	at net.gegy1000.psf.server.ServerEventHandler.onWorldUpdate(ServerEventHandler.java:33) ~[ServerEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_113_ServerEventHandler_onWorldUpdate_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by Gegy** [comment]
Seems to me like it's not an issue with this mod, but rather B.A.S.E. Perhaps try exploding a B.A.S.E ore with TNT to see if the same crash occurs?

**Comment by Gegy** [comment]
Okay, looking at the B.A.S.E code, it could be caused by some mod adding ores with it incorrectly. Is there by any chance a string in the log like:
`Could not find Item for name: <something>`
