### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ChaosKuchenTV** [gegy1000/PracticalSpaceFireworks#9]
i have a following crash :

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 4/27/18 7:50 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Could not initialize class net.gegy1000.psf.server.fluid.PSFFluidRegistry
	at net.gegy1000.psf.server.block.PSFBlockRegistry.onRegisterBlocks(PSFBlockRegistry.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_PSFBlockRegistry_onRegisterBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.gegy1000.psf.server.block.PSFBlockRegistry.onRegisterBlocks(PSFBlockRegistry.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_PSFBlockRegistry_onRegisterBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 196566696 bytes (187 MB) / 419430400 bytes (400 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                                       | Signature                                |
	|:----- |:----------------- |:------------ |:-------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.2       | minecraft.jar                                | None                                     |
	| UCH   | mcp               | 9.42         | minecraft.jar                                | None                                     |
	| UCH   | FML               | 8.0.99.99    | forge-1.12.2-14.23.1.2555.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.23.1.2555 | forge-1.12.2-14.23.1.2555.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar                  | None                                     |
	| UCE   | psf               | 0.1.0-dev    | practical-space-fireworks-0.1.0.2-modjam.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.2.9655 Compatibility Profile Context' Renderer: 'ATI Radeon HD 5750 '
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: ATI Radeon HD 5750  GL version 3.2.9655 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7 CPU 870 @ 2.93GHz

**Comment by Ardragos** [comment]
Update your forge version, had the same issue at first

**Comment by LordOfDeath35** [comment]
I have the same issue and after updating the forge version, it still doesn´t work.

**Comment by LordOfDeath35** [comment]
Open the "practical-space-fireworks-0.1.0.2-modjam" file with WinRar, open the file "net", then the file "gegy1000", then the file "psf", and then delete the file named "PracticalSpaceFireworks.class". Also look on the Curse Website, which Mods are required to play this mod and install them. After that just open Minecraft and it should work. (It at least works for me)
